/*
 * ReImprimirFactura.java
 *
 * Created on 20 de agosto de 2008, 01:39 PM
 */
package view;

import Imprimir.Impresora;
import daoHibernateImpl.FacturaDaoImpl;
import javax.swing.JOptionPane;
import model.Factura;

/**
 *
 * @author  Administrador
 */
public class ReImprimirFactura extends javax.swing.JInternalFrame {

    /** Creates new form ReImprimirFactura */
    public ReImprimirFactura() {
        initComponents();
        this.setClosable(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Reimprimir Facturas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jTextField1.setToolTipText("Ingrese el código de la factura a imprimir");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, -1));

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel2.setText("Codigo de factura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    Factura factura = new Factura();
    FacturaDaoImpl factManager = new FacturaDaoImpl();
    int codigoFactura = 0;
    boolean buenosDatos = true;
    if (jTextField1.getText() != null) {
        try {
            codigoFactura = Integer.parseInt(jTextField1.getText().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "El codigo de factura debe ser un valor numérico");
            buenosDatos = false;
        }
        if (buenosDatos == true) {
            factura = factManager.facturaPorCodigo(codigoFactura);
             Impresora impresora = new Impresora();
             impresora.imprimir(factura);
             jTextField1.setText("");
             JOptionPane.showMessageDialog(rootPane, "La factura: "+factura.getId()+" ha sido reimpresa");
             
        }
    }else{
            JOptionPane.showMessageDialog(rootPane, "El codigo de factura no debe de estar vacío");
    }

}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
