/*
 * SearchUniqueFact.java
 *
 * Created on 17 de agosto de 2008, 12:17 PM
 */

package view;

import daoHibernateImpl.FacturaDaoImpl;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.Factura;

/**
 *
 * @author  luisj
 */
public class SearchUniqueFact extends javax.swing.JInternalFrame {

    public JDesktopPane pane;
    /** Creates new form SearchUniqueFact */
    public SearchUniqueFact(JDesktopPane pane) {
        initComponents();
        this.pane = pane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBusqueda = new javax.swing.JTextField();
        jButtonbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Busqueda Factura por Numero");

        jTextFieldBusqueda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButtonbuscar.setText("BUSCAR");
        jButtonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de Factura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonbuscar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonbuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuscarActionPerformed
// TODO add your handling code here:
    FacturaDaoImpl factDao = new FacturaDaoImpl();
    try{
    Factura factTemp =factDao.facturaPorCodigo(Integer.parseInt(jTextFieldBusqueda.getText()));
    if(!jTextFieldBusqueda.getText().equalsIgnoreCase("")){
    if(factTemp == null){
        JOptionPane.showMessageDialog(this, "factura No encontrada intente de Nuevo","Factura No Encontrada",JOptionPane.INFORMATION_MESSAGE);
        jTextFieldBusqueda.setText("");
    }else{
        FacturaView factView = new FacturaView(factTemp,pane,false);
        pane.add(factView);
        factView.setVisible(true);
        
    }
    }
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Solo Digite Numeros","Atencion",JOptionPane.WARNING_MESSAGE);
         jTextFieldBusqueda.setText("");
    
    }
}//GEN-LAST:event_jButtonbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables

}
