/*
 * ReportesFacturacion.java
 *
 * Created on 17 de agosto de 2008, 10:43 AM
 */
package view;

import Reportes.ModuloFacturacion;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrador
 */
public class ReportesFacturacion extends javax.swing.JInternalFrame {

    /** Creates new form ReportesFacturacion */
    public ReportesFacturacion() {
        initComponents();
        this.setClosable(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jNameCliente = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        comboMesAnuladas = new javax.swing.JComboBox();
        comboMesDesde = new javax.swing.JComboBox();
        comboMesHasta = new javax.swing.JComboBox();
        comboMes = new javax.swing.JComboBox();
        comboMesSinImp = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jAnioDesde = new javax.swing.JTextField();
        jAnioHasta = new javax.swing.JTextField();

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Reportes de Facturas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jCodigo.setToolTipText("Ingrese el codigo de factura");
        jPanel1.add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));
        jCodigo.getAccessibleContext().setAccessibleDescription(null);

        jLabel2.setText("Por codigo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel3.setText("Anuladas por mes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel4.setText("Por cliente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jNameCliente.setToolTipText("Ingrese el nombre del cliente");
        jPanel1.add(jNameCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, -1));

        jButton3.setText("Generar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel5.setText("Por fecha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel6.setText("Por mes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButton4.setText("Generar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel7.setText("Exoneradas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton5.setText("Generar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        comboMesAnuladas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12" }));
        comboMesAnuladas.setToolTipText("Ingrese el mes a consultar");
        jPanel1.add(comboMesAnuladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        comboMesDesde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12" }));
        comboMesDesde.setToolTipText("Ingrese el mes de la fecha DESDE");
        jPanel1.add(comboMesDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        comboMesHasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12" }));
        comboMesHasta.setToolTipText("Ingrese el mes de la fecha HASTA");
        jPanel1.add(comboMesHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        comboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12" }));
        comboMes.setToolTipText("Ingrese el mes a consultar");
        jPanel1.add(comboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        comboMesSinImp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12"}));
        comboMesSinImp.setToolTipText("Ingrese el mes a consultar");
        jPanel1.add(comboMesSinImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton6.setText("Generar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jAnioDesde.setToolTipText("Año DESDE (ej: 2012)");
        jPanel1.add(jAnioDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 60, -1));

        jAnioHasta.setToolTipText("Año Hasta (ej: 2012)");
        jPanel1.add(jAnioHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    ModuloFacturacion factManager = new ModuloFacturacion();
    try {
        int mes = Integer.parseInt(jCodigo.getText().toString());
        factManager.facturaPorCodigo(mes);
    } catch (Exception e) {
        System.out.println(e.getStackTrace());
    }
    JOptionPane.showMessageDialog(rootPane, "El reporte ha sido creado");

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    ModuloFacturacion factManager = new ModuloFacturacion();
    int mes = Integer.parseInt(comboMes.getSelectedItem().toString());
    factManager.facturasPorMes(mes);
    JOptionPane.showMessageDialog(rootPane, "El reporte ha sido creado");
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    ModuloFacturacion factManager = new ModuloFacturacion();
    String nombreCliente = jNameCliente.getText().toString();
    factManager.facturasPorCliente(nombreCliente);
    System.out.println("El NOMBRE DIGITADO FUE: " + jNameCliente.getText().toString());
    JOptionPane.showMessageDialog(rootPane, "El reporte ha sido creado");
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    ModuloFacturacion factManager = new ModuloFacturacion();
    int mes = Integer.parseInt(comboMesAnuladas.getSelectedItem().toString());
    factManager.facturasAnuladasPorMes(mes);
    JOptionPane.showMessageDialog(rootPane, "El reporte ha sido creado");
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    ModuloFacturacion factManager = new ModuloFacturacion();
    int mes = Integer.parseInt(comboMesSinImp.getSelectedItem().toString());
    factManager.facturasSinImpuesto(mes);
    JOptionPane.showMessageDialog(rootPane, "El reporte ha sido creado");
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    ModuloFacturacion factManager = new ModuloFacturacion();
    int anioDesde = Integer.parseInt(jAnioDesde.getText().toString());
    int anioHasta = Integer.parseInt(jAnioHasta.getText().toString());
    int mesDesde = Integer.parseInt(comboMesDesde.getSelectedItem().toString());
    int mesHasta = Integer.parseInt(comboMesHasta.getSelectedItem().toString());
    factManager.facturasPorFecha(anioDesde, anioHasta, mesDesde, mesHasta);
    JOptionPane.showMessageDialog(rootPane, "El reporte ha sido creado");
}//GEN-LAST:event_jButton6ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboMes;
    private javax.swing.JComboBox comboMesAnuladas;
    private javax.swing.JComboBox comboMesDesde;
    private javax.swing.JComboBox comboMesHasta;
    private javax.swing.JComboBox comboMesSinImp;
    private javax.swing.JTextField jAnioDesde;
    private javax.swing.JTextField jAnioHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNameCliente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
